# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('link', models.CharField(max_length=200, verbose_name='Link')),
                ('time_added', models.DateTimeField(verbose_name='Time Added')),
                ('author', models.CharField(max_length=200, verbose_name='Author')),
                ('published', models.CharField(max_length=200, verbose_name='Published')),
            ],
        ),
    ]
